package entity;
// Generated Oct 13, 2018 5:50:50 PM by Hibernate Tools 4.3.1



/**
 * ProOrderDetails generated by hbm2java
 */
public class ProOrderDetails  implements java.io.Serializable {


     private Integer orderDetails;
     private ProOrder proOrder;
     private Product product;
     private int proQty;

    public ProOrderDetails() {
    }

    public ProOrderDetails(ProOrder proOrder, Product product, int proQty) {
       this.proOrder = proOrder;
       this.product = product;
       this.proQty = proQty;
    }
   
    public Integer getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Integer orderDetails) {
        this.orderDetails = orderDetails;
    }
    public ProOrder getProOrder() {
        return this.proOrder;
    }
    
    public void setProOrder(ProOrder proOrder) {
        this.proOrder = proOrder;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getProQty() {
        return this.proQty;
    }
    
    public void setProQty(int proQty) {
        this.proQty = proQty;
    }




}


